### ISSUE TITLE
Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/mkdocs#1]
Hi @FernandoCelmer, we need to adjust a few things first to move forward, ok? ✨

We need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by FernandoCelmer** [comment]
Hello @luxonauta ,
I opened a pull request with the project's standardization changes.  You can validate if necessary by this link: https://github.com/dracula/mkdocs/pull/2

**Comment by luxonauta** [comment]
Awesome! 💜✨
